name: Update Providers

on:
  schedule:
    - cron: "0 2 * * *" # Run nightly at 2 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Restore APIpie cache
        uses: actions/cache@v4
        with:
          path: cmd/apipie/cache.db
          key: apipie-cache-${{ hashFiles('cmd/apipie/cache.go') }}
          restore-keys: |
            apipie-cache-
      - name: Generate OpenRouter models
        run: go run ./cmd/openrouter/main.go
      - name: Generate APIpie models
        env:
          APIPIE_DISPLAY_NAME_API_KEY: ${{ secrets.APIPIE_DISPLAY_NAME_API_KEY }}
          APIPIE_API_KEY_NOTIFY_USER: ${{ secrets.APIPIE_API_KEY_NOTIFY_USER }}
        run: go run ./cmd/apipie/main.go ./cmd/apipie/cache.go
      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v5
        with:
          commit_message: "chore: auto-update OpenRouter and APIpie provider configs"
          branch: main
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: actions-user <actions@github.com>
